import worker,{home,daysFromToday,weeksFromToday,howLongUntil,percentQuestion,conversionQuestion,fractionQuestion,ratioQuestion,loanQuestion,salaryQuestion,gradeQuestion,compoundInterestQuestion,discountQuestion,tipQuestion,areaQuestion,volumeQuestion,sitemap,sitemapIndex,sitemapSegment} from '../src/index.js';
const assert=(x,m)=>{if(!x)throw new Error(m)};
assert(daysFromToday(30,new Date('2026-09-21T12:00:00Z')).includes('October 21, 2026'),'30-day date failed');
assert(weeksFromToday(6,new Date('2026-09-21T12:00:00Z')).includes('November 2, 2026'),'6-week date failed');
assert(howLongUntil('5-pm').includes('How Long Until 5:00 PM?'),'time route failed');
assert(sitemap().includes('/days-from-today/90/'),'sitemap missing core URL');
assert(percentQuestion(20,50).includes('20% of 50 is 10'),'percentage pSEO failed');
assert(conversionQuestion(10,'kg-to-lb').includes('22.04622622 lb'),'conversion pSEO failed');
assert(sitemap().includes('/convert/10-kg-to-lb/'),'sitemap missing conversion URL');
assert(conversionQuestion(1,'cup-to-ml').includes('236.5882365 mL'),'cup conversion failed');
assert(conversionQuestion(60,'mph-to-kmh').includes('96.56064 km/h'),'speed conversion failed');
assert(fractionQuestion(3,4).includes('75%'),'fraction pSEO failed');
assert(ratioQuestion(12,18).includes('2 : 3'),'ratio pSEO failed');
assert(sitemap().includes('/days-from-today/365/'),'sitemap missing 365-day page');
assert(sitemap().includes('/fraction/3-4/'),'sitemap missing fraction URL');
assert(sitemap().includes('/ratio/12-to-20/'),'sitemap missing ratio URL');
assert(loanQuestion(10000,6,5).includes('$193.33'),'loan pSEO failed');
assert(salaryQuestion(60000).includes('$28.85'),'salary pSEO failed');
assert(gradeQuestion(87,100).includes('87%'),'grade pSEO failed');
assert(sitemap().includes('/loan/10000-at-6-for-5-years/'),'sitemap missing loan pSEO URL');
assert(sitemap().includes('/salary/60000-to-hourly/'),'sitemap missing salary pSEO URL');
assert(sitemap().includes('/grade/87-out-of-100/'),'sitemap missing grade pSEO URL');
assert(compoundInterestQuestion(5000,7,10,200).includes('$44,665.27'),'compound interest pSEO failed');
assert(discountQuestion(20,100).includes('$80.00'),'discount pSEO failed');
assert(tipQuestion(20,80,2).includes('$48.00'),'tip pSEO failed');
assert(areaQuestion('circle',5).includes('78.539816'),'area pSEO failed');
assert(volumeQuestion('box',4,5,10).includes('200 cubic units'),'volume pSEO failed');
assert(sitemap().includes('/compound-interest/5000-at-7-for-10-years-with-200-monthly/'),'sitemap missing compound URL');
assert(sitemap().includes('/discount/20-percent-off-100/'),'sitemap missing discount URL');
assert(sitemap().includes('/tip/20-percent-on-80-split-2/'),'sitemap missing tip URL');
assert(sitemap().includes('/area/circle-radius-5/'),'sitemap missing area URL');
assert(sitemap().includes('/volume/box-4-by-5-by-10/'),'sitemap missing volume URL');
assert(sitemapIndex().includes('/sitemaps/time-date.xml')&&sitemapIndex().includes('/sitemaps/money.xml'),'sitemap index missing segments');
assert(sitemapSegment('converters').includes('/convert/10-kg-to-lb/')&&!sitemapSegment('converters').includes('/loan/'),'converter sitemap segmentation failed');
assert(sitemapSegment('money').includes('/loan/10000-at-6-for-5-years/'),'money sitemap segmentation failed');
assert(home().includes('application/ld+json'),'home JSON-LD missing');
assert(sitemap().includes('/loan-calculator/'),'sitemap missing loan calculator');
assert(sitemap().includes('/compound-interest-calculator/'),'sitemap missing compound interest calculator');
const loan=await worker.fetch(new Request('https://example.com/loan-calculator/'));assert(loan.status===200,'loan calculator route failed');
const loanSeo=await worker.fetch(new Request('https://example.com/loan/10000-at-6-for-5-years/'));assert(loanSeo.status===200,'loan pSEO route failed');
const salarySeo=await worker.fetch(new Request('https://example.com/salary/60000-to-hourly/'));assert(salarySeo.status===200,'salary pSEO route failed');
const gradeSeo=await worker.fetch(new Request('https://example.com/grade/87-out-of-100/'));assert(gradeSeo.status===200,'grade pSEO route failed');
const compSeo=await worker.fetch(new Request('https://example.com/compound-interest/5000-at-7-for-10-years-with-200-monthly/'));assert(compSeo.status===200,'compound pSEO route failed');
const discSeo=await worker.fetch(new Request('https://example.com/discount/20-percent-off-100/'));assert(discSeo.status===200,'discount pSEO route failed');
const tipSeo=await worker.fetch(new Request('https://example.com/tip/20-percent-on-80-split-2/'));assert(tipSeo.status===200,'tip pSEO route failed');
const areaSeo=await worker.fetch(new Request('https://example.com/area/circle-radius-5/'));assert(areaSeo.status===200,'area pSEO route failed');
const volumeSeo=await worker.fetch(new Request('https://example.com/volume/box-4-by-5-by-10/'));assert(volumeSeo.status===200,'volume pSEO route failed');
const gpa=await worker.fetch(new Request('https://example.com/gpa-calculator/'));assert(gpa.status===200,'GPA route failed');
const pace=await worker.fetch(new Request('https://example.com/pace-calculator/'));assert(pace.status===200,'pace route failed');
const r=await worker.fetch(new Request('https://example.com/percentage-calculator/'));assert(r.status===200,'worker route failed');
console.log('All AnswerCalcs tests passed.');
